// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "iPhonekimdae"
#define SECRET_PASS "kimdae9003"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a14gmfijpbj0qb-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIIChDCCAWygAwIBAgIUd8VLnTbwLfoE6kwNqiHY7EN8DUQwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTEyODA5MDYw
MloXDTQ5MTIzMTIzNTk1OVowFDESMBAGA1UEAxMJZmluYWxleGFtMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEyHR5lR2vaQCxxYmdyN5358tIqF6auwiAEJh4yeTA
HrF/x3Xl3VEwvOt5KvF1g0YWW1SaUP9NzW8A2qt8YFoYf6NgMF4wHwYDVR0jBBgw
FoAUbqzJaI2VC4qdI14tbm5XN3/9cG8wHQYDVR0OBBYEFBP2NdNVMES7fsrmt1JR
+a0vIbKMMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEB
CwUAA4IBAQBpI439nuFVV/GwQkBfaH8CT0pyLirr+/JOPYhV4m9btg+fakATX6FP
u82UpgUDG07ppscNVsQe/c05eFPE5RhWs5NX70aAO2AZ78Fdu7+oFUbYsH9KQc3C
opl4VlN+l4WZIkVxnbFTvelzeQ6Rtyv9Rx1OtEvzA/6YApb8mk8mNcW2NktovP6s
/p9leiYMTpVmQS72VvAM0U3Ngxl7bFoMeC7qGPmv3vATGMW6FF1IK85xB5gXFeVD
mXSvJdyxLd5yaaLCAXtDFmQV82txp6eoJ7rKrU/Ot0Gjq5fxhAjEPkzMdHEGsBZi
gjc7QB7qCwJjSjfdklTod3ouBzyZeesw
-----END CERTIFICATE-----
)";
